'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const CATS={all:['全部',''],sight:['景点','#206f87'],food:['美食','#b56a26'],history:['潜伏','#7958a0'],relax:['休息','#52705b']}, ICONS={sight:'山',food:'食',history:'迹',relax:'休'};
const DEFAULT=()=>({version:1,days:[[],[],[]],wishlist:[],stays:{},modes:{},resolved:{}});
function validateState(s){if(!s||s.version!==1||!Array.isArray(s.days)||s.days.length!==3)throw Error('不是有效的重庆行程文件');const ids=new Set(PLACES.map(p=>p.id)),seen=new Set();for(const arr of [...s.days,s.wishlist||[]]){if(!Array.isArray(arr)||arr.length>100)throw Error('行程格式不正确');for(const id of arr){if(!ids.has(id)||seen.has(id))throw Error('行程含未知或重复地点');seen.add(id)}}const v=DEFAULT();v.days=s.days.map(a=>[...a]);v.wishlist=[...(s.wishlist||[])];for(const [k,n] of Object.entries(s.stays||{})){if(ids.has(k)&&Number.isFinite(n)&&n>=0&&n<=1440)v.stays[k]=n}for(const [k,n] of Object.entries(s.modes||{})){if(/^[0-2]:[\w-]+:[\w-]+$/.test(k)&&['transit','walk','drive'].includes(n))v.modes[k]=n}for(const [k,p] of Object.entries(s.resolved||{})){if(ids.has(k)&&p&&Number.isFinite(p.lng)&&Number.isFinite(p.lat)&&p.lng>105&&p.lng<110&&p.lat>28&&p.lat<32){v.resolved[k]={lng:p.lng,lat:p.lat,name:String(p.name||'').slice(0,150),address:String(p.address||'').slice(0,300),precision:'poi',source:'高德地点搜索 · 用户确认'}}}return v}
let state=DEFAULT(),loadNotice='';try{const hash=new URLSearchParams(location.hash.slice(1)).get('plan');if(hash){state=validateState(JSON.parse(decodeURIComponent(escape(atob(hash)))));loadNotice='已打开分享的行程快照'}else if(window.EMBEDDED_PLAN){state=validateState(window.EMBEDDED_PLAN)}else{const s=localStorage.getItem('cq-plan-v1');if(s)state=validateState(JSON.parse(s))}}catch(e){loadNotice='行程数据无法读取，已保留空白行程：'+e.message}
let category='all',view='explore',day=0,selected=null,query='',region='',generation=0,results={},map,clusters,lines,markers={},amapReady=false,amapLoading=null;
function place(id){const p=PLACES.find(p=>p.id===id);return p?{...p,...state.resolved[id],name:p.name}:null}
function assigned(id){const d=state.days.findIndex(a=>a.includes(id));return d>=0?d:state.wishlist.includes(id)?3:-1}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4000)}
function save(){try{localStorage.setItem('cq-plan-v1',JSON.stringify(state))}catch{toast('浏览器无法保存，请导出行程备份')}generation++;render();}
function assign(id,d){if(!place(id)||!Number.isInteger(d)||d< -1||d>3)throw Error('无效的地点或日期');state.days=state.days.map(a=>a.filter(x=>x!==id));state.wishlist=state.wishlist.filter(x=>x!==id);if(d===3)state.wishlist.push(id);else if(d>=0)state.days[d].push(id);save();if(selected===id)showDetail(id,false)}
function minutes(id){return state.stays[id]??place(id).minutes}const fmt=n=>n>=60?`${Math.floor(n/60)}小时${n%60?Math.round(n%60)+'分':''}`:`${Math.round(n)}分钟`;
function gcjToWgs(lng,lat){const a=6378245,ee=.006693421622965943,x=lng-105,y=lat-35,pi=Math.PI;let dl=-100+2*x+3*y+.2*y*y+.1*x*y+.2*Math.sqrt(Math.abs(x));dl+=(20*Math.sin(6*x*pi)+20*Math.sin(2*x*pi))*2/3;dl+=(20*Math.sin(y*pi)+40*Math.sin(y/3*pi))*2/3;dl+=(160*Math.sin(y/12*pi)+320*Math.sin(y*pi/30))*2/3;let dn=300+x+2*y+.1*x*x+.1*x*y+.1*Math.sqrt(Math.abs(x));dn+=(20*Math.sin(6*x*pi)+20*Math.sin(2*x*pi))*2/3;dn+=(20*Math.sin(x*pi)+40*Math.sin(x/3*pi))*2/3;dn+=(150*Math.sin(x/12*pi)+300*Math.sin(x/30*pi))*2/3;const rad=lat/180*pi,magic=1-ee*Math.sin(rad)**2;dl=dl*180/((a*(1-ee))/(magic*Math.sqrt(magic))*pi);dn=dn*180/(a/Math.sqrt(magic)*Math.cos(rad)*pi);return [lat-dl,lng-dn]}
function latlng(p){return p.wgs&&!state.resolved[p.id]?p.wgs:gcjToWgs(p.lng,p.lat)}
function wgsToGcj(lng,lat){let x=lng,y=lat;for(let i=0;i<4;i++){const [ay,ax]=gcjToWgs(x,y);x+=lng-ax;y+=lat-ay}return [x,y]}
for(const p of PLACES){if(p.wgs){[p.lng,p.lat]=wgsToGcj(p.wgs[1],p.wgs[0])}}
function startMap(){if(!window.L){$('#mapStatus').textContent='地图库未加载，地点清单仍可用';return}map=L.map('map',{zoomControl:false}).setView(gcjToWgs(106.565,29.56),13);L.control.zoom({position:'topright'}).addTo(map);const attribution='© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>';
const layers={
 '浅色地图':L.tileLayer('https://basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',{maxZoom:19,attribution:attribution+' · © <a href="https://carto.com/attributions" target="_blank" rel="noopener">CARTO</a>'}),
 '标准地图':L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution})
};
for(const layer of Object.values(layers)){
 layer.on('tileload',()=>{if(map.hasLayer(layer))$('#mapStatus').textContent='拖动探索 · 点击聚合点放大'});
 layer.on('tileerror',()=>{if(map.hasLayer(layer))$('#mapStatus').textContent='底图加载失败，可用右侧图层按钮切换地图'});
}
layers['浅色地图'].addTo(map);
L.control.layers(layers,null,{position:'topright'}).addTo(map);
clusters=L.markerClusterGroup({maxClusterRadius:45,showCoverageOnHover:false,spiderfyOnMaxZoom:true,iconCreateFunction:c=>L.divIcon({html:String(c.getChildCount()),className:'cluster',iconSize:[42,42]})}).addTo(map);lines=L.layerGroup().addTo(map);new ResizeObserver(()=>map.invalidateSize()).observe($('#map'));}
function filtered(){return PLACES.map(p=>place(p.id)).filter(p=>(category==='all'||p.cat===category)&&(!region||p.area===region)&&(!query||(p.name+p.note+p.area+p.address).toLowerCase().includes(query.toLowerCase())))}
function renderMap(){if(!map)return;clusters.clearLayers();markers={};for(const p of filtered()){if(p.lng==null)continue;const idx=state.days[day<3?day:0].indexOf(p.id);const mark=L.marker(latlng(p),{title:p.name,icon:L.divIcon({className:'marker-wrap',html:`<div class="pin ${p.precision==='poi'?'':'approx'}" style="--pin:${CATS[p.cat][1]}"><span>${view==='plan'&&idx>=0?idx+1:ICONS[p.cat]}</span></div>`,iconSize:[30,35],iconAnchor:[15,32]})}).bindTooltip(esc(p.name));mark.on('click',()=>showDetail(p.id));markers[p.id]=mark;clusters.addLayer(mark)}drawLines()}
const legKey=(d,a,b)=>`${d}:${a}:${b}`;
function routeKey(a,b,mode){return `${a.id}:${a.lng},${a.lat}>${b.id}:${b.lng},${b.lat}:${mode}`}
function currentResult(a,b,mode){return results[routeKey(a,b,mode)]}
function drawLines(){if(!map)return;lines.clearLayers();if(day===3)return;const arr=state.days[day].map(place);let actual=0;for(let i=1;i<arr.length;i++){const a=arr[i-1],b=arr[i],mode=state.modes[legKey(day,a.id,b.id)]||'transit',r=currentResult(a,b,mode);if(a.lng==null||b.lng==null)continue;if(r?.paths?.length){r.paths.forEach(path=>L.polyline(path,{color:'#236c87',weight:5,opacity:.85}).addTo(lines));actual++}else L.polyline([latlng(a),latlng(b)],{color:'#326b83',weight:3,dashArray:'7 9',opacity:.75}).addTo(lines)}$('#routeLegend').textContent=arr.length<2?'选择地点后，按游览顺序连线':`${actual?'实线：已查询路线 · ':''}虚线：游览顺序示意，非道路`}
function renderList(){const ps=filtered();$('#resultCount').textContent=`${ps.length} 个地点 · ${ps.filter(p=>p.lng!=null).length} 个有位置`;
$('#places').innerHTML=ps.map(p=>`<article class="place-card"><div class="cat-icon ${p.cat}">${ICONS[p.cat]}</div><div class="place-main"><button class="place-name" data-open="${p.id}">${esc(p.name)}</button><div class="place-meta">${esc(p.area)} · ${fmt(minutes(p.id))}</div>${p.preference?`<span class="tag ${p.preference==='特别想去'?'favorite':''}">${p.preference}</span>`:''}${p.precision==='unlocated'?'<span class="tag">分店 / 地址待选</span>':p.precision==='area'?'<span class="tag">片区参考位置</span>':''}</div><button class="pick ${assigned(p.id)>=0?'selected':''}" data-pick="${p.id}" aria-label="安排${esc(p.name)}">${assigned(p.id)>=0?assigned(p.id)===3?'待':assigned(p.id)+1:'+'}</button></article>`).join('')||'<p class="empty">没有找到匹配地点，试试其他片区或关键词。</p>'}
function render(){renderList();renderPlan();renderMap();$('#planCount').textContent=state.days.flat().length}
function changeView(v){view=v;$('#explore').hidden=v!=='explore';$('#plan').hidden=v!=='plan';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderMap();}
function navURL(a,b,mode){const type={transit:'bus',walk:'walk',drive:'car'}[mode];return 'https://uri.amap.com/navigation?'+new URLSearchParams({from:`${a.lng},${a.lat},${a.name}`,to:`${b.lng},${b.lat},${b.name}`,mode:type,policy:mode==='drive'?'1':'0',src:'chongqing-trip',coordinate:'gaode',callnative:'0'})}
function searchURL(p){return 'https://uri.amap.com/search?'+new URLSearchParams({keyword:'重庆 '+p.name,city:'重庆',src:'chongqing-trip',callnative:'0'})}
function renderPlan(){const arr=day===3?state.wishlist:state.days[day];$('#days').innerHTML=[0,1,2,3].map(d=>`<button class="${day===d?'active':''}" data-day="${d}">${d===3?'待定':`第 ${d+1} 天`}</button>`).join('');let travel=0,known=0;for(let i=1;i<arr.length;i++){const a=place(arr[i-1]),b=place(arr[i]),m=state.modes[legKey(day,a.id,b.id)]||'transit',r=currentResult(a,b,m);if(r?.seconds!=null){travel+=Math.ceil(r.seconds/60);known++}}const stays=arr.reduce((s,id)=>s+minutes(id),0);
$('#planBody').innerHTML=arr.length?`<div class="summary"><strong>${arr.length} 个地点 · 停留 ${fmt(stays)}</strong><small>${day===3?'待定清单，不计入三天路线':arr.length<2?'再添加一个地点即可比较交通':known===arr.length-1?`交通 ${fmt(travel)} · 合计约 ${fmt(stays+travel)}（不含额外等候）`:`交通待查 ${arr.length-1-known} 段${known?' · 已查 '+fmt(travel):''}；尚不能计算全天总时长`}</small></div>${day!==3?'<button id="refreshRoutes" class="primary">查询 / 刷新当天交通</button>':''}<div>${arr.map((id,i)=>{const p=place(id),a=i?place(arr[i-1]):null,k=a?legKey(day,a.id,id):'',mode=state.modes[k]||'transit',r=a?currentResult(a,p,mode):null;return `${a&&day!==3?`<div class="leg"><select aria-label="前往${esc(p.name)}的交通方式" data-mode="${k}"><option value="transit" ${mode==='transit'?'selected':''}>公共交通</option><option value="walk" ${mode==='walk'?'selected':''}>步行</option><option value="drive" ${mode==='drive'?'selected':''}>驾车 / 打车</option></select><p>${r?.seconds!=null?`约 <b>${fmt(Math.ceil(r.seconds/60))}</b> · ${(r.distance/1000).toFixed(1)} km<br>${esc(r.description)}<br><small>查询于 ${esc(r.time)} · 出发前请刷新</small>`:r?.error?esc(r.error):'尚未查询交通时间'}</p>${a.lng!=null&&p.lng!=null?`<a href="${esc(navURL(a,p,mode))}" target="_blank" rel="noopener">在高德查看路线${a.precision!=='poi'||p.precision!=='poi'?'（先核验起终点）':''}</a>`:'请先选定分店位置'}</div>`:''}<article class="stop"><div class="stop-title"><span class="number">${i+1}</span><button class="place-name" data-open="${id}">${esc(p.name)}</button></div><div class="stop-tools"><label>停留 <input type="number" min="0" max="1440" step="5" data-stay="${id}" value="${minutes(id)}" aria-label="${esc(p.name)}停留分钟"> 分</label><button data-move="${id}" data-dir="-1" ${i===0?'disabled':''} aria-label="上移${esc(p.name)}">↑</button><button data-move="${id}" data-dir="1" ${i===arr.length-1?'disabled':''} aria-label="下移${esc(p.name)}">↓</button><button data-remove="${id}" aria-label="移除${esc(p.name)}">移除</button></div></article>`}).join('')}</div>${day!==3?nearbyHTML(arr):''}`:`<div class="empty"><span class="big">${day===3?'＋':'0'+(day+1)}</span><h2>${day===3?'还没决定的，先放这里。':'这一天，由你来安排。'}</h2><p>从地图或地点清单中选一个想去的地方，加入${day===3?'待定清单':'第 '+(day+1)+' 天'}。<br>选满两个地点后，就能查询沿途交通。</p><button class="primary" data-view="explore">去选地点</button></div>`}
function nearbyHTML(ids){const pts=ids.map(place).filter(p=>p.lng!=null);if(!pts.length)return '';const dist=(a,b)=>{const rad=Math.PI/180,x=(a.lng-b.lng)*Math.cos((a.lat+b.lat)/2*rad),y=a.lat-b.lat;return Math.hypot(x,y)*111.32};const near=PLACES.map(p=>place(p.id)).filter(p=>['food','history'].includes(p.cat)&&p.lng!=null&&assigned(p.id)<0).map(p=>({p,d:Math.min(...pts.map(t=>dist(p,t)))})).filter(x=>x.d<1.5).sort((a,b)=>a.d-b.d).slice(0,4);return near.length?`<div class="nearby"><h3>这些也在附近</h3><p class="muted">与已选地点的直线距离，仅作浏览参考；跨江、台阶可能绕路。</p>${near.map(({p,d})=>`<button data-open="${p.id}">${ICONS[p.cat]} ${esc(p.name)}<small>直线约 ${(d*1000).toFixed(0)} 米${p.precision!=='poi'?' · 位置待核实':''}</small></button>`).join('')}</div>`:''}
function showDetail(id,pan=true){selected=id;const p=place(id),photo=PHOTOS[id],d=assigned(id);$('#detail').hidden=false;$('#detail').innerHTML=`<button class="close" id="closeDetail" aria-label="关闭地点详情">×</button>${photo?`<figure><img src="${photo.url}" alt="${esc(p.name)}实景照片" loading="lazy"><figcaption><a href="${photo.source}" target="_blank" rel="noopener">${photo.credit} · 图片裁切展示</a></figcaption></figure>`:''}<div class="detail-content"><span class="tag">${CATS[p.cat][0]} · ${esc(p.area)}</span><h2 style="margin-top:12px">${esc(p.name)}</h2><p>${esc(p.note)}</p>${state.resolved[id]?.name?`<p>已选地图地点：${esc(state.resolved[id].name)}</p>`:''}${p.address?`<p>地址：${esc(p.address)}</p>`:''}<p class="muted">${p.precision==='poi'?'已查到地点坐标，实际入口请现场确认。':p.precision==='unlocated'?'尚无可核实位置，请选定具体分店。':p.precision==='area'?'地图仅显示片区参考位置，不代表准确店址。':'地图为大致位置，建议查询前核验实际入口。'}<br>建议停留 ${fmt(minutes(id))}，可在行程中调整。</p>${p.source&&p.source.startsWith('http')?`<a class="muted" href="${esc(p.source)}" target="_blank" rel="noopener">查看地点资料来源</a>`:''}<div class="button-row">${[0,1,2,3].map(n=>`<button data-assign="${id}" data-to="${n}" class="${d===n?'primary':''}">${n===3?'待定':`第 ${n+1} 天`}${d===n?' ✓':''}</button>`).join('')}</div>${d>=0?`<button data-remove="${id}">从行程移除</button>`:''}<div class="button-row"><button id="resolvePlace">核验位置 / 选分店</button><a href="${esc(searchURL(p))}" target="_blank" rel="noopener">高德搜索</a></div><label class="muted">地点搜索词（可修改）<input id="poiKeyword" class="poi-keyword" value="${esc(p.name.replace(/候选/g,'').replace(/周边$/,''))}" aria-label="高德地点搜索词"></label><div id="resolveResults" class="resolve-list"></div></div>`;$('#detail img')?.addEventListener('error',e=>{e.target.hidden=true;e.target.parentElement.querySelector('figcaption').insertAdjacentText('afterbegin','图片暂未加载 · ')});if(pan&&map&&p.lng!=null){map.setView(latlng(p),Math.max(map.getZoom(),15));if(markers[id]&&map.hasLayer(markers[id]))markers[id].openTooltip()}}
function closeDetail(){$('#detail').hidden=true;selected=null}
function connectAMap(){if(amapReady)return Promise.resolve();if(amapLoading)return amapLoading;let key='',code='';try{key=sessionStorage.getItem('cq-amap-key')||'';code=sessionStorage.getItem('cq-amap-code')||''}catch{}if(!key||!code){$('#settings').showModal();return Promise.reject(Error('请先配置高德 Key，当前不会计算虚构时间'))}amapLoading=new Promise((resolve,reject)=>{window._AMapSecurityConfig={securityJsCode:code};const s=document.createElement('script');const timer=setTimeout(()=>{amapLoading=null;reject(Error('高德连接超时，请检查网络、Key 与域名白名单'))},18000);s.src='https://webapi.amap.com/maps?v=2.0&key='+encodeURIComponent(key)+'&plugin=AMap.PlaceSearch,AMap.Transfer,AMap.Walking,AMap.Driving';s.onload=()=>{clearTimeout(timer);if(window.AMap?.PlaceSearch){amapReady=true;resolve()}else{amapLoading=null;reject(Error('高德未就绪，请核对 Key 和安全密钥'))}};s.onerror=()=>{clearTimeout(timer);amapLoading=null;reject(Error('高德加载失败，请检查网络'))};document.head.appendChild(s)});return amapLoading}
function amSearch(p,keyword){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('地点查询超时')),15000);new AMap.PlaceSearch({city:'重庆',citylimit:true,pageSize:6,extensions:'all'}).search(keyword||p.name.replace(/（.*?方向）/g,'').replace(/候选/g,'').replace(/周边$/,''),(status,r)=>{clearTimeout(timer);if(status==='complete'&&r.poiList?.pois?.length)resolve(r.poiList.pois);else reject(Error('未找到匹配门店，请在高德中核验原名称'))})})}
async function resolveSelected(){const id=selected;if(!id)return;const keyword=$('#poiKeyword')?.value.trim();try{await connectAMap();const p=place(id);$('#resolveResults').textContent='正在查询重庆的候选位置…';const pois=await amSearch(p,keyword);if(selected!==id)return;$('#resolveResults').innerHTML='<p class="muted">确认名称和地址后再选定，地图将使用该准确位置。</p>';for(const poi of pois){const b=document.createElement('button');b.textContent=poi.name;const small=document.createElement('small');small.textContent=poi.address||'地址未提供';b.append(small);b.onclick=()=>{state.resolved[id]={lng:poi.location.getLng(),lat:poi.location.getLat(),name:poi.name,address:typeof poi.address==='string'?poi.address:'',precision:'poi',source:'高德地点搜索 · 用户确认'};save();showDetail(id);toast('已更新地点位置')};$('#resolveResults').append(b)}}catch(e){toast(e.message);if(selected===id&&$('#resolveResults'))$('#resolveResults').textContent=e.message}}
function amapRoute(a,b,mode){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('路线查询超时，请重试')),18000);const opts={city:'重庆',cityd:'重庆',extensions:'all'},service=mode==='transit'?new AMap.Transfer({...opts,policy:AMap.TransferPolicy.LEAST_TIME}):mode==='walk'?new AMap.Walking():new AMap.Driving({policy:AMap.DrivingPolicy.LEAST_TIME,extensions:'all'});service.search([a.lng,a.lat],[b.lng,b.lat],(status,r)=>{clearTimeout(timer);if(status!=='complete'){reject(Error('高德未返回路线：'+(r?.info||status)));return}const route=mode==='transit'?r.plans?.[0]:r.routes?.[0];if(!route||!Number.isFinite(route.time)){reject(Error('没有可用的交通方案'));return}const paths=[],names=[];const append=path=>{if(path?.length)paths.push(path.map(pt=>gcjToWgs(pt.lng??pt.getLng?.(),pt.lat??pt.getLat?.())).filter(p=>p.every(Number.isFinite)))};if(mode==='transit'){for(const seg of route.segments||[]){append(seg.transit?.path);if(seg.transit?.lines?.length)names.push(seg.transit.lines.map(l=>l.name).join(' / '));else if(seg.transit_mode==='WALK')names.push('步行')}}else for(const step of route.steps||[])append(step.path);resolve({seconds:route.time,distance:route.distance||0,paths:paths.filter(p=>p.length>1),description:mode==='transit'?names.join(' → ')||'公共交通方案':mode==='walk'?'步行路线':'驾车预计时间，不含候车',time:new Date().toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})})})})}
async function refreshRoutes(){const d=day;if(d===3)return;const ids=[...state.days[d]];if(ids.length<2)return;try{await connectAMap()}catch(e){toast(e.message);return}const unresolved=ids.map(place).find(p=>p.precision!=='poi'||p.lng==null);if(unresolved){showDetail(unresolved.id);toast('请先核验 '+unresolved.name+' 的位置，再查询交通');await resolveSelected();return}const token=generation;const button=$('#refreshRoutes');if(button){button.disabled=true;button.textContent='正在查询…'}for(let i=1;i<ids.length;i++){if(token!==generation||day!==d)break;const a=place(ids[i-1]),b=place(ids[i]),mode=state.modes[legKey(d,a.id,b.id)]||'transit',key=routeKey(a,b,mode);try{const r=await amapRoute(a,b,mode);if(token!==generation)break;results[key]=r}catch(e){if(token!==generation)break;results[key]={error:e.message}}}renderPlan();drawLines();if(token===generation)toast('查询已结束；无结果的路段会显示原因')}
function snapshot(){return JSON.stringify(state)}function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)}
async function exportPortable(){try{const sources={};for(const [k,url] of Object.entries({css:'style.css',leafletCss:'vendor/leaflet.css',clusterCss:'vendor/markercluster.css',leaflet:'vendor/leaflet.js',cluster:'vendor/markercluster.js',data:'data.js',app:'app.js'})){if(window.PORTABLE_SOURCES){sources[k]=window.PORTABLE_SOURCES[k];continue}const r=await fetch(url);if(!r.ok)throw Error('文件读取失败');sources[k]=await r.text()}const doc=document.documentElement.cloneNode(true);doc.querySelectorAll('script,link[rel="stylesheet"]').forEach(e=>e.remove());doc.querySelector('#map').innerHTML='';doc.querySelector('#map').removeAttribute('class');doc.querySelector('#map').removeAttribute('style');doc.querySelector('#detail').hidden=true;doc.querySelector('#detail').innerHTML='';doc.querySelectorAll('dialog').forEach(e=>e.removeAttribute('open'));doc.querySelector('#toast').className='';doc.querySelector('#amapKey').value='';doc.querySelector('#amapCode').value='';const style=document.createElement('style');style.textContent=sources.leafletCss+'\n'+sources.clusterCss+'\n'+sources.css;doc.querySelector('head').append(style);const script=text=>{const el=document.createElement('script');el.textContent=text.replace(/<\/script/gi,'<\\/script');doc.querySelector('body').append(el)};script('window.EMBEDDED_PLAN='+snapshot().replace(/</g,'\\u003c')+';window.PORTABLE_SOURCES='+JSON.stringify(sources).replace(/</g,'\\u003c')+';');for(const k of ['leaflet','cluster','data','app'])script(sources[k]);download('重庆三日漫游.html','<!doctype html>\n'+doc.outerHTML,'text/html;charset=utf-8');toast('便携网页版已下载，包含当前行程')}catch(e){toast('导出失败。请通过本地预览或已发布网页打开后再导出。')}}
async function copyShare(){if(location.protocol==='file:'||['localhost','127.0.0.1'].includes(location.hostname)){toast('本地地址不能给他人访问，请下载便携网页版分享');return}const u=new URL(location.href);u.hash='plan='+encodeURIComponent(btoa(unescape(encodeURIComponent(snapshot()))));try{await navigator.clipboard.writeText(u.href);toast('行程链接已复制；接收者仍需有网站访问权限')}catch{const t=document.createElement('textarea');t.value=u.href;$('#share').append(t);t.select();toast('浏览器未允许复制，请手动复制文本框中的链接')}}
$('#filters').innerHTML=Object.entries(CATS).map(([k,v])=>`<button data-cat="${k}" class="${k===category?'active':''}">${v[0]}</button>`).join('');[...new Set(PLACES.map(p=>p.area))].forEach(a=>{const o=document.createElement('option');o.value=a;o.textContent=a;$('#area').append(o)});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const ds=b.dataset;if(ds.view){changeView(ds.view)}if(ds.cat){category=ds.cat;document.querySelectorAll('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));renderList();renderMap()}if(ds.open)showDetail(ds.open);if(ds.pick)showDetail(ds.pick);if(ds.assign)assign(ds.assign,Number(ds.to));if(ds.remove)assign(ds.remove,-1);if(ds.day){day=Number(ds.day);generation++;renderPlan();renderMap()}if(ds.move){const a=day===3?state.wishlist:state.days[day],i=a.indexOf(ds.move),j=i+Number(ds.dir);if(j>=0&&j<a.length){[a[i],a[j]]=[a[j],a[i]];save()}}if(b.id==='closeDetail')closeDetail();if(b.id==='resolvePlace')resolveSelected();if(b.id==='refreshRoutes')refreshRoutes()});
document.addEventListener('change',e=>{const d=e.target.dataset;if(d.stay){const v=Number(e.target.value);if(Number.isFinite(v)&&v>=0&&v<=1440){state.stays[d.stay]=v;save()}else{toast('停留时间应为0–1440分钟');renderPlan()}}if(d.mode){state.modes[d.mode]=e.target.value;save();if(amapReady)refreshRoutes()}});
$('#search').oninput=e=>{query=e.target.value;renderList();renderMap()};$('#area').onchange=e=>{region=e.target.value;renderList();renderMap()};$('#fitBtn').onclick=()=>{if(!map)return;const ps=filtered().filter(p=>p.lng!=null);if(ps.length)map.fitBounds(ps.map(latlng),{padding:[55,55],maxZoom:15})};$('#settingsBtn').onclick=()=>$('#settings').showModal();$('#shareBtn').onclick=()=>$('#share').showModal();$('#copyLink').onclick=copyShare;$('#exportJson').onclick=()=>download('重庆三天行程.json',snapshot(),'application/json');$('#exportHtml').onclick=exportPortable;
$('#importJson').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>200000)throw Error('文件过大');const next=validateState(JSON.parse(await f.text()));state=next;results={};save();$('#share').close();changeView('plan');toast('行程已导入')}catch(err){toast('导入失败：'+err.message)}e.target.value=''};
$('#connect').onclick=async()=>{const key=$('#amapKey').value.trim(),code=$('#amapCode').value.trim();if(!key||!code){$('#connectionStatus').textContent='请填写 Key 和安全密钥';return}try{sessionStorage.setItem('cq-amap-key',key);sessionStorage.setItem('cq-amap-code',code);amapReady=false;amapLoading=null;$('#connectionStatus').textContent='正在连接并测试地点查询…';await connectAMap();await amSearch(place('luohan'));$('#connectionStatus').textContent='连接成功，可以核验位置并查询交通。';toast('高德查询已连接')}catch(e){amapReady=false;$('#connectionStatus').textContent=e.message}};
$('#clearKey').onclick=()=>{try{sessionStorage.removeItem('cq-amap-key');sessionStorage.removeItem('cq-amap-code')}catch{}amapReady=false;amapLoading=null;$('#amapKey').value='';$('#amapCode').value='';$('#connectionStatus').textContent='配置已清除；已加载的地图脚本会在关闭页面后释放。'};
startMap();render();if(loadNotice)toast(loadNotice);
if(document.modelContext?.registerTool){for(const tool of [{name:'read_chongqing_plan',description:'读取当前三日重庆行程和候选地点',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({plan:state,places:PLACES.map(({id,name,cat})=>({id,name,cat}))})},{name:'assign_chongqing_place',description:'把已存在的地点加入某一天或待定；day=0,1,2为三天，3为待定，-1为移除',inputSchema:{type:'object',properties:{id:{type:'string'},day:{type:'integer',minimum:-1,maximum:3}},required:['id','day'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{assign(input.id,input.day);return {plan:state}}}])try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}

document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});
